version: '3.3'

services:
    mysql-db:
        image: mysql
        hostname: mysql-db
        ports:
        - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=leafeon
        - MYSQL_DATABASE=leafeon
        networks:
        - leafeon
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        hostname: zookeeper
        ports:
        - '2181:2181'
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
        - leafeon
    kafka:
        image: 'bitnami/kafka:latest'
        hostname: kafka
        ports:
        - '9092:9092'
        environment:
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        networks:
        - leafeon
    neo4j:
        image: neo4j:3.5.0
        hostname: neo4j
        ports:
        - 7474:7474
        - 7687:7687
        networks:
        - leafeon
        environment:
        - NEO4J_AUTH=none
#        - NEO4J_AUTH=neo4j/neo4j
networks:
    leafeon:
        driver: bridge
