server:
    port: 9999

spring.data.neo4j.uri: bolt://localhost:7687

spring.datasource:
    url: jdbc:mysql://localhost:3306/leafeon
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: leafeon



spring.jpa:
    hibernate.ddl-auto: create
    properties.hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

kafka:
    bootstrapAddress: ${KAKFA_ADDRESS:localhost:9092}
    order-topic: order-topic


logging:
    level:
        org.springframework.data: DEBUG